HANGAR_DOOR_STATE = 'close'  # 机库门状态为打开（open）、关闭(close)、异常（error）
HANGAR_TD_BAR_STATE = 'close'  # 上下推拉杠状态，打开为open,关闭为close,异常为error
HANGAR_LR_BAR_STATE = 'close'  # 左右推拉杠状态，打开为open,关闭为close，异常为error
HANGAR_BAR_STATE = 'close'  # 初始状态推拉杆为打开状态
AIR_CONDITION_STATE = 'close'  # 空调状态，打开为open,关闭为close，异常为error
STAT_CONNECT_STATE = 'close'  # 当前设备串口连接状态
# self.wfcstate = wfcstate  # 无线充电当前状态
UAV_CONTROLLER_STATE = 'close'  # 无人机手柄初始状态为关机
NIGHT_LIGHT_STATE = 'close'  # 夜间灯状态，默认close
ALARM_STATE = "close"  # 警报灯是否开启
OUT_LIFT_STATE = "unknown"
UPDOWN_LIFT_STATE = "up"  # 升降台状态
TURN_LIFT_STATE = "back"  # 旋转台状态
# SHUTTER_DOOR_STATE = "close"  # 卷帘门状态
SHADE_WINDOW_STATE = "close"  # 百叶窗状态
IS_RAIN_STATE = '0'  # 是否下雨
WIND_DIRECTION_VALUE = '北风'  # 风向
WIND_SPEED_VALUE = '0'  # 风速
TEMPERATURE_VALUE = 0.0  # 温度
HUMIDITY_VALUE = 0.0  # 湿度
PARKING_TEMPERATURE_VALUE = 0.0  # 停机坪温度
PARKING_HUMIDITY_VALUE = 0.0  # 停机坪湿度
RAIN_FALL_VALUE = 0.0  # 降雨量
SMOKE_VALUE = 0  # 无烟
GPS_VALUE = "0.0,0.0"
IS_UPS_STATE = 0  # 市电正常,是否使用UPS
INDOOR_TEM_VALUE = 0.0  # 机库内温度
INDOOR_HUM_VALUE = 0.0  # 机库内湿度
PRESSURE_VALUE = 100  # 外部大气压
# self.airstate = airstate
HANGAR_VERSION = "V1.0"  # 机库版本
# 自动充电
RUN_AUTO_CHARGE = 0
# FLY_BACK = -1
CHARGE_UUID = ""
CHARGE_NUM = 0
